

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-uri: bW9uZ29kYitzcnY6Ly9hY2hyYWY6YWNocmFmMTIzNEBjbHVzdGVyMC5zMm1vbXltLm1vbmdvZGIubmV0Lw==
#kubectl create secret generic mongodb-connection-string-secret --from-literal=connection-string='your-mongo-connection-string'
